/**
 * Chrome Whatshop
 *
 * Detect shopping cart solution and tools concerning privacy run on current page and send back to background page.
 * Some part of this script was referred from Wappalyzer (Firefox) and AppSniffer.
 *
 * @author Eberhard Burck <ebbudev@gmail.com>
 * @author Laila Abazzouh <laba.ext+whatshop@gmail.com>
 * @author Bao Nguyen <contact@nqbao.com>
 * @license GPLv3
 **/


var _apps = {};
var doc = document.documentElement;
var a
var url = document.URL;
var vers;
var url_test = {
    'NA': /google\./i
};
if (url_test['NA'].test(url)) {
    //send immediately back to background page for performance reason
    var jsonString = JSON.stringify(_apps);
    //alert(jsonString);
    var meta = document.getElementById('whatshop_meta');
    meta.content = jsonString;

    //Notify Background Page
    var done = document.createEvent('Event');
    done.initEvent('ready', true, true);
    meta.dispatchEvent(done);
} else {

    // 0: detect by url
    var url_tests = {
        'EINSUNDEINS': /sess\/utn/i,
        'epages': /epages/i,
        'facebookshop': /facebook\.com/i,
        'Rakuten': /rakuten|tradoria/i,
        'Strato': /strato/i,
        'hood': /hood\.de/i,
        'T-Online': /eshop\.t-online/
    };

    for (t in url_tests)
    {
        if (t in _apps) continue;

        if (url_tests[t].test(url))
        {
            _apps[t] = -1;
        }
    }

    // 1: detect by meta tags
    var metas = doc.getElementsByTagName("meta");
    var meta_tests = {
        'generator': {
            'Cubecart': /cubecart/i,
            'Cosmoshop': /CosmoShop/,
            'Joomla': /joomla!?\s*([\d\.]+)?/i,
            'Drupal': /drupal\s*(.*)/i,
            'WordPress': /WordPress\s*(.*)/i,
      			'Piconda': /piconda\scluster\s*(.*)/i,
      			'WPML':/wpml\s*(.*)/i,
            'Woocommerce': /WooCommerce\s*(.*)/,
            //'Shopware': /shopware\s*(.*)/i,
            'X-Cart': /X-Cart\s*(.*)/i,
            'DataBecker': /web\sto\sdate\s*(.*)/i,
            'Siquando': /SIQUANDO\sShop\s*(.*)/i,
            'Contao': /Contao Open Source CMS/,
            'TYPO3': /TYPO3/i,
            'ez Publish': /eZ\s*Publish/i,
            'Pace Retail': /Pace\sRetail/i,
            'Presta': /Presta|PrestaShop|prestashop/,
            'RBS_change': /RBS Change/i,
            'Zen_Cart': /zen-cart/i,
            //XTC
            'commerceseo': /commerce:SEO|commerce:seo\sv3/i,
            'XTC_3': /xt:Commerce\s*v3/i,
            'XTC_Veyton': /xt:Commerce\s4/i,
            'X-Cart': /X-Cart\s*(.*)/i,
            'Oxatis': /oxatis/
        },
        'author': {
            'RedCart': /http\:\/\/(www\.)?redcart\.pl/,
            'Oxatis': /oxatis/
        }
    };

    for (var idx in metas)
    {
        var m = metas[idx];
        var name = m.name ? m.name.toLowerCase() : "";

        if (!meta_tests[name]) continue;

        for (var t in meta_tests[name])
        {
            if (t in _apps) continue;
            //alert(meta_tests[name][t]+':'+m.content);
            var r = meta_tests[name][t].exec(m.content);
            //alert (r[0]);
            if (r)
            {
                _apps[t] = r[1] ? r[1] : -1;
				//alert(_apps[t]);
            }
        }
    }

    // 2: detect by regexp
    var text = document.documentElement.outerHTML;
    var text_tests = {
        '4Sellers': /logicbase|4sellers/i,
        'Abacus': /exactabacus/i,
        'Aconon': /www\.aconon\.de/,
        'Aconon': /www\.aconon\.de/,
        'Actinic': /actinic|sellerdeck/i,
        'Actebis': /actebis/,
        'APT': /apt-(trading|webshop)/,
        'ABAS': /\/abas/,
        'Bigcommerce': /cdn\d+\.bigcommerce\.com/i,
        'EINSUNDEINS': /(ssl\.kundenserver\.de)|(\?sessid=)|(product_overview\.shopscript)|(generated by shop3)/i,
        'Afterbuy': /afterbuy\/.de|www.afterbuy.de/i,
        'Cactushop': /cactushop/i,
        //'Cosmoshop': /www\.cosmoshop\.de|zaunz/i,
        'CP-Shop': /Contentpapst/,
        //'DataBecker': /s2d/i,
        'Ecomas': /ecomas-cms/,
        // 'Econda': /emos_kdnr/i,
        'Electronicsales': /es\:shop/i,
        'ekmPowershop': /\/ekmps\//i,
        'epages': /<div class=\"BoxContainer\">|[^a-zA-Z]epages/,
        'epages now': /epages.*@dev/,
        //'T-Online': /TOnline\/lib-min/&&/epages/,
        'eSellerPro': /esellerpro/i,
        // 'eTracker': /etracker\.de\/(lnk){0,1}cnt/i,
        'Firepages': /firepages/i,
        'Gsshopbuilder': /gs-shopbuilder/,
        'Hotdigital': /hotdigital/,
        'JIMDO': /jimcdn/i,
        //'IAI': /[^a-zA-Z]iai[^a-zA-Z]/i,
        'Intershop': /\/intershop\.static|intershop/i,
        'I-ways': /\/i-ways/i,
        'i-sklep': /href="http:\/\/i-sklep\.pl/i,
        'JTL': /JTL-Shop|JTLSHOP|(JTL-Shop[\s]{0,1}3)|\sjtl\s|jtl_token|jtlversion/,/*jtl\.php,name="JTLSHOP"*/
        'LiquidShop': /liquidshop/i,
        'Magento': /(var BLANK_URL = '[^>]+js\/blank\.html')^(simplecommerce)|\/varien\/|<link [rel="stylesheet" type="text\/css"]*[rel="icon"]* href="https?:\/\/[a-z0-9\-_.~]+[a-z0-9\-_.~\/]*\/skin\/frontend\/|<link (rel="icon"|rel="shortcut icon") href="https?:\/\/[a-z0-9\-_.~]+[a-z0-9\-_.~\/]*\/media\/favicon\/default\/|copyright\s©\smagento,\sinc.|frontend\/Magento\/|Magento_Theme/img,
        'Magento_MRG': /(trustedrating\.css)|(tax-details(.*)\/lieferung\/)/i,
        'Mauve': /\MauveShop|Mauve\sWebshopsystem/,
        'MiCommerce': /miBaseURL/i,
        'MondoShop': /(Mondo Shop)|(mondo\.media)/i,
        'MUV': /yanis42/,
        'OMECO': /omeco\sGmbH|omeco.|omeco/,
        //'OXID_ESALES': /OXID\s+eSales|oxid-esales\.com|oxid\.css|\/oxid/i,
        'OXID_ESALES': /OXID\s+eSales|oxid-esales\.com|oxid\.css|source\/out\/flow/i,
        'Plentymarkets': /plentysystems|plentymarkets|plentyid/i,
        'Plentymarkets_v6': /content="plentymarkets"/,
        'Powerboutique' : /\/boutique\/[^.]*\.cfm\?/i,
        'Presta': /Prestashop|PrestaShop|prestashop/i,
        'Rakuten': /rakuten|tradoria/i,
        'Redback': /redback|adeo\s*group/i,
        'SEOshop': /SEOshop\sGroup\sB\.V\.|seoshop\/[0-9]{6}.js/i,
        'Lightspeed': /lightspeedhq/&&/assets.webshopapp.com/&&/Lightspeed\sNetherlands\sB.V./i,
        'Shoper': /<div id="shoper-foot">/,
		    'Shoplo': /cdn.shoplo.com/i,
        'Shopware': /jquery\.shopware\.js|web\/cache|engine\/Shopware/,
        'Simplecommerce':  /powered\sby\ssimplecommerce/,
        'Smartstore': /SMOMAbsolute|MPopupMenu|smartstore/i,
        'Smartstore-Image': /smartstore-startseitenheader-micron/,
        'Strato': /strato(.*)epages/i,
        'Strato': /storeWebRoot|Strato\/GUI/,
        'Sote':  /((\/|\.)sote\.pl)|(frontend\/theme\/default2\/)/i,
        'Tradoro':  /tradoro\.pl/i,
        'Venda': /bin\/venda/,
        'Visualsoft': /visualsoft/,
        'Websale': /websale/i,
        'Wix': /[Ww]ix\.com/,
        'Xanario': /xanario/i,
        'Xonic': /xonic/i,
        //XTC
        'Gambio': /([Gg]ambio|\/content\.php\?coID=\d)|(\/gambio)/,
        'XTC_3': /(xt:Commerce v3)^(xtcModified)|XTCsid^(xtcModified)/i,
        'XTC_Veyton': /(xt:Commerce 4(\.0|\.1)?)|VEYTON|(templates\/xtc4\/)/i,
        'xtcModified': /xtcModified|\/xtc5\/|modified-shop\.org/i,
        'Zen_Cart':  /zenid/i,
        'WordPress': /<link rel=("|')stylesheet("|') [^>]+wp-content|includes/i,
        'MODx': /(<a[^>]+>Powered by MODx<\/a>|var el= \$\('modxhost'\);|<script type=("|')text\/javascript("|')>var MODX_MEDIA_PATH = "media";)/i,
        'osCommerce': /(<a[^>]*osCsid)/i,
        'Opencart': /[Bb]y\sOpenCart/&&/[Ff]or\sOpenCart/&&/OpenCart/i,
        'OpenCart': /opencart\.com/&&/index\.php\?route=[*]/,
        'Opencart': /catalog\/view\/theme/,
        'OpenCart': /(Powered By <a href=("|')[^>]+OpenCart|route = getURLVar\(("|')route)/i,
        'Bigware': /bigware/i,
        'CS Cart':  /CS-Cart\s-\sShopping\sCart\sSoftware/i,
        'Cubecart':/(Powered by <a href=.http:\/\/www\.cubecart\.com|<p[^>]+>Powered by CubeCart)/i,
        'CouchCommerce' : /ng-app="CouchCommerceApp"/i,
        'dashCommerce': /(name\="\_\_EVENTTARGET" id\="\_\_EVENTTARGET")^(logicbase)/i,
        'Demandware': /<[^>]+demandware.static/,
        'Drupal': /(<script [^>]+drupal\.js|jQuery\.extend\(Drupal\.settings, \{|Drupal\.extend\(\{ settings: \{|<link[^>]+sites\/(default|all)\/themes\/|<style[^>]+sites\/(default|all)\/(themes|modules)\/)/i,
        'Drupal Commerce': /id\=\"block\-commerce\-cart\-cart|class\=\"commerce\-product\-field/i,
        'eZ Publish': /<meta name=("|')generator("|') [^>]+eZ Publish/i,
        'Hybris':/\/sys_master\/|\/hybr\//,
        'nopCommerce':  /(<!\-\-Powered by nopCommerce|Powered by: <a[^>]+nopcommerce)|CoreVision.nopcommerce.Theme/i,
        'osCSS': /<body onload=("|')window\.defaultStatus='oscss templates';("|')/i,
        'PhPepperShop': /PhPepperShop/i,
        'Powergap':  /(s\d\d)\.php\?shopid=\1/,
        'Quick.Cart': /<a href="[^>]+opensolution\.org\/">Powered by/i,
        'ReadyPro' : /\/ReadySkins\//i,
        'Shop-Application': /(whost[1-9]*\.fr)|shop-application\.com/i,
        'Shopify': /cdn\.shopify\.com|[sS]hopify\.[cC]heckout/,
        'TomatoCart': /<meta name=("|')generator("|') [^>]+TomatoCart/i,
        'TYPO3': /(<meta name=("|')generator("|') [^>]+TYPO3|<(script[^>]* src|link[^>]* href)=[^>]*fileadmin)/i,
        'Ubercart': /<script[^>]* src=("|')[^>]*uc_cart\/uc_cart_block\.js/i,
        'Vignette': /<[^>]+?=("|')(vgn\-ext|vgnext)/i,
        'VirtueMart': /<div id=("|')vmMainPage/,
        'VirtueMart': /virtuemart/,
        'Wolf CMS':  /<a href=("|')[^>]+wolfcms.org.+Wolf CMS.+inside/i,
        'WordPress': /(<link rel=("|')stylesheet("|') [^>]+wp-content|<meta name=("|')generator("|') [^>]+WordPress)/i,
        'Websphere': /wcsstore/i,
        'X-Cart': /\s+xcart/,
		    'HESCOM-Shop': /HESCOM\sWeb\sFramework|HESCOM-Software|www.hescomshop.de|www.hescom.de|HescomShop/mg,
        'AFS Shop': /bez.replace|savewkorb/,
        //'Applicas': /public\/cache/,//pattern checken
        'Geos Shop': /geossql/,
        'MK-Mall24': /mall24/,
        'My eShop': /my-eshop/,
        'Store Systems': /store-systems/,
        //'Strait Shop': ,
        'Superstore': /ingrammicro/,
        'Truition': /truition/,
        'Vione': /vioneshop/,
        //'Web Business Shop': web business shop 3.,
        'XonSoft': /xonsoft/,
	    	'Mallux':/mallux\/mallux|www.mallux.de/g,
        //Wordpress-Plugins
        'Wellcommerce-Plugin': /themes\/wellcommerce/,
        'Woocommerce': /plugins\/woocommerce|woocommerce-pagination/,
        'WPML': /wpml-/,
        //CMS/
        'Jigoshop': /plugins\/jigoshop-ecommerce/,
        'Shopp': /wp-content\/themes\/shopplugin/,
		    'IONOS': /ionos-logo&ionos-brand|"(?:http(s)?:\/\/)w{3}.ionos.[a-zA-Z]+.websites.homepage.[a-zA-Z]+"/,
        'cactushop': /cactushop/,
        'CCV-Shop': /CCVShop/,
        'Joomshopping': /com_jshopping/,
        /* *****************************************************************************

                                TRUSTEDSHOPS-ERKENNUNG

        ****************************************************************************** */
        //'Trustbadge ohne Variante': /trustedshops.com\/js/ && /.*'variant'\:\s\''/,
        /*'Trustbadge - Reviews': /trustedshops.com\/js/ && /.*'variant'\:\s\'reviews'/,
        'Trustbadge - Custom': /trustedshops.com\/js/ && /.*'variant'\:\s\'custom'/,
        'Trustbadge - Custom Reviews': /trustedshops.com\/js/ && /.*'variant'\:\s\'custom_reviews'/,
        'Trustbadge - Default': /trustedshops.com\/js/ && /.*'variant'\:\s\'default'/,
        'Trustbadge - Text': /var_tsid*[=]*'*'/&&/.*'variant'\:\s\'text'/,
        'Trustbadge - Small': /var_tsid*[=]*'*'/&&/.*'variant'\:\s\'small'/,*/
        'Trustedshops - Shopify Plugin': /trustedshops_shopify\.js/,
        'Trustbadge - Skript eingebunden': /trustedshops.js/,
        'Trustcard via TB': /id="Container_db8d3657bdbe440c985ae127463eaad4"/,
        'Trustcard - DIV': /div\sid="tscard4_db8d3657bdbe440c985ae127463eaad4"\sclass="customCheckout_db8d3657bdbe440c985ae127463eaad4/,
        'TS-Checkout-DIV': /div\sid="trustedShopsCheckout"\sstyle="display\:\snone\;"/,
        'TS-Checkout-DIV + Produktdaten': /span\sclass="tsCheckoutProductItem"/,
        /*'Review Sticker ohne Variante': /trustedshops.com\/reviews\/tsSticker\/tsSticker\.js/ && /.*variant\:\s\''/,
        'Review Sticker - skyscraper_vertical': /trustedshops.com\/reviews\/tsSticker\/tsSticker\.js/ && /variant\:\s\'skyscraper_vertical'/,
        'Review Sticker - skyscraper_horizontal': /trustedshops.com\/reviews\/tsSticker\/tsSticker\.js/ && /variant\:\s\'skyscraper_horizontal'/,
        'Review Sticker - vertical': /trustedshops.com\/reviews\/tsSticker\/tsSticker\.js/ && /variant\:\s\'vertical'/,
        */
        'TS-Widget': /widgets\.trustedshops\.com\/reviews\/tsSticker\/tsProductStickerSummary\.js/,
        'Testimonial': /trustedshops.com\/reviews\/tsSticker\/tsSticker\.js/ && /variant\:\s\'testimonial\'/,
        'Product Review Sticker': /trustedshops.com\/reviews\/tsSticker\/tsProductSticker.js/,
        'StarSummary': /\/\/widgets.trustedshops.com\/reviews\/tsSticker\/tsProductStickerSummary.js/,
        'Verlinkung auf TS-Profil': /href="http:\/\/www.trustedshops.de\/profil\/X|href=“https:\/\/www.trustedshops.de\/bewertung\info_X|href="https:\/\/www.trustedshops.com\/shop\/certificate.php?shop_id=X|href="https:\/\/www.trustedshops.de\/shop\/certificate.php?shop_id=X|href="http:\/\/www.trustedshops.fr\/evaluation\/info_X|href="http:\/\/www.trustedshops.es\/evaluacion\/info_X|href="http:\/\/www.trustedshops.pl\/opinia\/info_X|href="http:\/\/www.trustedshops.nl\/verkopersbeoordeling\/info_X|href="http:\/\/www.trustedshops.be\/fr\/evaluation\/info_X|href="http:\/\/www.trustedshops.be\/nl\/verkopersbeoordeling\/info_X|href="http:\/\/www.trustedshops.it\/valutazione-del-negozio\/info_X/,
        'Alter Käuferschutz': /value="X/&&/name="shop_id"/&&/\saction="https:\/\/www.trustedshops.com\/shop\/protection.php"/,
        'TS-Widget': /trustedshops.com\/bewertung\/widget\/widgets\/X/,

        /* **************************************************************************

                                  TRUSTED SHOPS-ERKENNUNG END

           *************************************************************************** */
		    'NewCart': /w{3}.newcart.[a-zA-z]+\/.[a-zA-z]+\//i,
        'TEST': /TESTPATTERN-CONTAINER/
    };

    for (t in text_tests)
    {
        if (t in _apps) continue;

        if (text_tests[t].test(text))
        {
            _apps[t] = -1;
        }
    }

    // 3: detect by script tags
    var scripts = doc.getElementsByTagName("script");

    var script_tests = {
        'Joomla': /\/components\/com_/,
        'Ubercart': /uc_cart/i,
        'StarSummary': /widgets.trustedshops.com\/reviews\/tsSticker\/tsProductStickerSummary.js"/,
        'Magento': /static\/_requirejs|Magento_Ui/,
        'Shopware': /engine\/Shopware\/Plugins/,
        'T-Online': /TOnline\/lib-min\/package-sf.js/,
        'OpenCart': /catalog\/view\/javascript\/common.js/
    };

    for (var idx in scripts)
    {
        var s = scripts[idx];
        if (!s.src) continue;
        s = s.src;

        for (var t in script_tests)
        {
            if (t in _apps) continue;
            if (script_tests[t].test(s))
            {
                _apps[t] = -1;
            }
        }
    }

    // 4: detect by domains
    // TODO: rakuten

    // 5: detect by inline javascript
    var js_tests = {
        'Drupal': function() {
            return window.Drupal != null;
        },
        'Shop-Application': function() {
            return window.formulaire_dynamique_check != null;
        },
        'TomatoCMS': function() {
            return window.Tomato != null;
        },
        'JIMDO': function() {
            return window.jimdoData != null;
        }
    };

    for (t in js_tests)
    {
        if (t in _apps) continue;

        if (js_tests[t]())
        {
            _apps[t] = -1;
            //_apps[t].info = js_tests[t]();??
        }
    }

    /* *********************Rich Snippets******************************** */
    var scriptTag = document.getElementsByTagName('script');
    if (document.querySelector('script[type="application/ld+json"]')!== null){
    var jsonLD = JSON.parse(document.querySelector('script[type="application/ld+json"]').innerHTML);
    for (var i = 0; i < scriptTag.length; i++) {
      continue;
     }
    }

    /********** RS via Sticker: Konfi Abfrage für erfolgreiche Funktion von RS-Check ************/
    //if (jsonLD !== undefined){ var prRSPublisher = jsonLD['review']['0']['publisher']['name'];}
    var tsLink = /www.trustedshops.com\/buyerrating\/info_/;    //if (tsLink !== undefined){console.log("tslink found");}
    var micro_Orga = document.querySelector('div[itemtype="http://schema.org/Organization"]');    //if (typeof micro_Orga !== null){console.log("micro orga found");}
    var micro_local = document.querySelector('div[itemtype="http://schema.org/LocalBusiness"]');   // if (micro_local !== 'undefined'){console.log("micro local found");}
    var micro_AR = document.querySelector('div[itemtype="https://schema.org/AggregateRating"]');     //if (micro_AR !== 'undefined'){console.log("AR found");}
    var micro_ratVal = document.querySelector('div[itemprop=ratingValue]');
    var rdfa_vocab = document.querySelector('div[vocab="http://schema.org/"]');
    var rdfa_aggRat = document.querySelector('div[property="aggregateRating"]');
    var rdfa_orga = document.querySelector('div[typeof="Organization"]');
    var rdfa_local = document.querySelector('div[typeof="LocalBusiness"]');

    // 6: detect TS Snippets
    var ts_tests = {
      /* ********************* Trustbadge****************************** */
        'Trustbadge - Reviews': function() {
            //console.log("reviews");
            return _tsConfig.variant === "reviews";

            if(_tsConfig.variant === "reviews"){
                return _tsConfig.variant === "reviews";
            }
        },
        'Trustbadge - Custom': function() {
            if (_tsConfig.variant == "custom"){
            if (_tsConfig.customElementId === ""){
               console.log("[TB - "+ _tsConfig.variant + "] No customElementId");
            }
            return _tsConfig.variant == "custom";
            }
        },
        'Trustbadge - Custom Reviews': function() {
            if (_tsConfig.variant == "custom_reviews"){
            if (_tsConfig.customElementId === ""){
               console.log("[TB - "+ _tsConfig.variant + "] No customElementId");
            }
            return _tsConfig.variant == "custom_reviews";
          }
        },
        'Trustbadge - Default': function() {
            return _tsConfig.variant == "default";
        },
        'Trustbadge - Text': function() {
            return _tsConfig.variant == "text";
        },
        'Trustbadge - Small': function() {
            return _tsConfig.variant == "small";
        },
        'Trustbadge ohne Variante': function() {
            return _tsConfig.variant == "";
        },
        'Trustbadge (disabled via Script)': function() {
          if(typeof _tsConfig.disableTrustbadge === undefined){
               return;
             }
            return _tsConfig.disableTrustbadge == "true";
        },
        'Trustbadge (responsive TB disabled)': function() {
          if(typeof _tsConfig.disableResponsive === undefined){
             return;
           }
           else if(_tsConfig.disableResponsive == "true"){
              return _tsConfig.disableResponsive == "true";
            }
            else return;
        },

      /* *********************mobile variants****************************** */
      'Responsive Trustbadge (floating)': function() {
        if(/*typeof*/ _tsConfig.responsive === undefined){
          console.log("[TB] Responsive Array not included in _tsConfig")
               return;
             }
        var tbRespVar = _tsConfig.responsive.variant;

        if (tbRespVar == "floating"){
          return _tsConfig.responsive.variant == "floating";
        }
      },
      'Responsive Trustbadge (floating_reviews)': function() {
        if(/*typeof */_tsConfig.responsive === undefined){
               return;
             }
        var tbRespVar = _tsConfig.responsive.variant;

        if (tbRespVar == "floating_reviews"){
          return _tsConfig.responsive.variant == "floating_reviews";
        }
      },
      'Responsive Trustbadge (default)': function() {
        if(/*typeof*/ _tsConfig.responsive === undefined){
               return;
             }
        var tbRespVar = _tsConfig.responsive.variant;

        if (tbRespVar == "default"){
          return _tsConfig.responsive.variant == "default";
        }
      },
      'Responsive Trustbadge (custom)':  function() {
        if(/*typeof */_tsConfig.responsive === undefined){
               return;
             }
        var tbRespVar = _tsConfig.responsive.variant;

        if (tbRespVar == "custom"){
          if (_tsConfig.responsive.customElementId === ""){
            console.log("[Responsive TB - " + _tsConfig.responsive.variant + "] No customElementId");
          }
          return _tsConfig.responsive.variant == "custom";
        }
      },
      /* *********************Rich Snippets******************************** */
      'Shop-SEO-Stars - LocalBusiness-Snippet (JSON-LD)': function() {
            if (jsonLD !== undefined){
            if ((jsonLD['@type'] == "LocalBusiness") && (jsonLD['image'] == "http://static.trustedshops.com/img/brand/e-trustedshops_black_145-60.png")){
            //console.log("LocalBusi JSONLD");
            return jsonLD;
            }
          }
        },
        'Shop-SEO-Stars - Organization-Snippet (JSON-LD)': function() {
          if (jsonLD !== undefined){
              if ((jsonLD['@type'] == "Organization") && (jsonLD['@type'] == "AggregateRating") ){
              //console.log("Organization JSONLD");
              return jsonLD;
              }
            }
          },
          //www.stempelservice.de
          'Shop-SEO-Stars - AggregateRating-Snippet (microdata)':  function() {
                if ((micro_AR !== undefined) && (tsLink !== undefined) && (micro_ratVal !== undefined)){
                //console.log("AggRat Micro");
                return micro_AR;
                }
            },
          'Shop-SEO-Stars - Organization-Snippet (microdata)':  function() {
                if ((micro_Orga !== undefined) && (tsLink !== undefined) && (micro_ratVal !== undefined)){
                //console.log("Orga Micro");
                return micro_Orga;
                }
            },
      		'Shop-SEO-Stars - LocalBusiness-Snippet (microdata)':  function() {
                if ((micro_local !== undefined) && (tsLink !== undefined) && (micro_ratVal !== undefined)){
                //console.log("LocalBusi Micro");
                return micro_local;
                }
          },
          //RDFa - no testsites - recognition not tested
      /*  'Shop-SEO-Stars - Organization-Snippet (RDFa)':  function() {
              if ((rdfa_orga !== undefined) && (tsLink !== undefined) && (rdfa_aggRat !== undefined)){
              //console.log("Orga RDFa");
              return rdfa_orga;
              }
          },
        'Shop-SEO-Stars - LocalBusiness-Snippet (RDFa)':  function() {
          if ((rdfa_local !== undefined) && (tsLink !== undefined) && (rdfa_aggRat !== undefined)){
          //console.log("Orga RDFa");
          return rdfa_local;
          }
      },*/
      'Product-SEO-Stars - via Sticker (JSON-LD)': function() {
            if(typeof _tsProductReviewsConfig == "undefined"){
              //console.log("PR undefined");
                   return;
                 }
            var prRSConfi = _tsProductReviewsConfig.richSnippets;

            if(prRSConfi == "on"){
            console.log("PR-Rich Snippets activated via _tsProductReviewsConfig");
              var jsonLD = JSON.parse(document.querySelector('script[type="application/ld+json"]').innerHTML);
            if (jsonLD !== undefined){ var prRSPublisher = jsonLD['review']['0']['publisher']['name'];
          /*}
            if (jsonLD !== undefined){*/
            if ((jsonLD['@type'] == "Product") && (jsonLD['image'] == "http://static.trustedshops.com/img/brand/e-trustedshops_black_145-60.png") && (prRSPublisher == "Trusted Shops GmbH")){
            //console.log("Product JSONLD");
            return jsonLD;
            }
          }
         }

        if(_tsProductReviewsConfig.richSnippets == "off"){
            //console.log("PR RS off");
          }
        },
        //rs via Testimonial
        'Rich Snippets via Sticker': function() {
          if (typeof _tsRatingConfig == "undefined"){
            //console.log ("typeof _tsRatingConfig: " + typeof _tsRatingConfig);
          }
           else {//console.log ("_tsRatingConfig != undefined ");
             if (_tsRatingConfig !== undefined){
             var srRSConfi = _tsRatingConfig.richSnippets;

             if(srRSConfi == "on"){
             console.log("[Shop review Sticker - " + _tsRatingConfig.variant +"] RS active");
             return srRSConfi;
             }
           }
         }
        },
        /* ********************* Shop Review Sticker****************************** */
        'Testimonial':function() {
          if(typeof _tsRatingConfig == "undefined"){
             //console.log("_tsRatingConfig.variant undefined");
             return;
           }
           else {
           var stickerVar = _tsRatingConfig.variant;
           if(stickerVar == "testimonial"){
              //console.log(_tsRatingConfig.variant);
              return _tsRatingConfig.variant == "testimonial";
            }
            return;
          }
        },
        'Review Sticker ohne Variante': function() {
          if(typeof _tsRatingConfig == "undefined"){
             //console.log("_tsRatingConfig.variant undefined");
             return;
           }
           else {
           var stickerVar = _tsRatingConfig.variant;
           if(stickerVar == ""){
              //console.log("_tsRatingConfig.variant empty");
              return _tsRatingConfig.variant == "";
            }
            return;
          }
        },
        'Review Sticker - skyscraper_vertical': function() {
          if(typeof _tsRatingConfig == "undefined"){
             //console.log("_tsRatingConfig.variant undefined");
             return;
           }
           else {
           var stickerVar = _tsRatingConfig.variant;
           if(stickerVar == "skyscraper_vertical"){
              //console.log(_tsRatingConfig.variant);
              return _tsRatingConfig.variant == "skyscraper_vertical";
            }
            return;
          }
        },
        'Review Sticker - skyscraper_horizontal': function() {
          if(typeof _tsRatingConfig == "undefined"){
             //console.log("_tsRatingConfig.variant undefined");
             return;
           }
           else {
           var stickerVar = _tsRatingConfig.variant;
           if(stickerVar == "skyscraper_horizontal"){
              //console.log(_tsRatingConfig.variant);
              return _tsRatingConfig.variant == "skyscraper_horizontal";
            }
            return;
          }
        },
        'Review Sticker - vertical':function() {
          if(typeof _tsRatingConfig == "undefined"){
             //console.log("_tsRatingConfig.variant undefined");
             return;
           }
           else {
           var stickerVar = _tsRatingConfig.variant;
           if(stickerVar == "vertical"){
              //console.log(_tsRatingConfig.variant);
              return _tsRatingConfig.variant == "vertical";
            }
            return;
          }
        },
        /* *********************ExitIntent******************************** */
        'Exit Intent Popup':function() {
          var EIP = document.querySelector('link[id="trustbadgeStyleSheettbExitIntent"]');
          if (EIP !== null){
            //console.log("EIP");
            return EIP;
          }
        },


    };

    if(typeof _tsConfig !== "undefined") {
        for (t in ts_tests)
        {
            if (t in _apps) continue;

            if (ts_tests[t]())
            {
                _apps[t] = -1;
            }
        }
    }

    // 7: detect version
    var version_tests = {

      //allg. Journal Version
      'OpenCart-Journal-Version': function() {
       vers  = document.getElementsByTagName("html")[0].getAttribute("data-jv");
            //console.log("X1: " + document.getElementsByTagName("html")[0].getAttribute("data-jv"));
            if (vers  !== undefined ){
                return vers ;
            }
        },
        'OpenCart-Journal2': function() {
            //$('html').hasClass('oc2');
            vers  = document.getElementsByTagName("html")[0].getAttribute("data-j2v");
            if (vers  !== undefined ){
                return vers ;
            }
        },
		/*'SEOshop': function() {
			var dir = document.querySelector('script[src$="apploader.js"]').getAttribute('src');
			//var name = dir.split('/').pop();
			//dir = dir.replace('/'+name,"");
				if (dir !== undefined ){
					console.log(dir);
					return dir;
				}
			},*/
      'Gambio': function() {
        //'shopVersion'   : 'v3.0.0.0',
        /*var scriptTag = document.getElementsByTagName('script');
        for (var i = 0; i < scriptTag.length; i++) {var gamVer=/shopVersion\'\s\s\s:\s\'v3.0.0.0/;
          if (scriptTag[i].innerHTML = gamVer ){console.log(gamVer)}
        }*/
          /*if (/\'shopVersion\'\s\s\s:\s\'v\s*(.*)/ !== 'undefined'){
              //return vers;
          }*/
      },


    };

var versName;
    for (t in version_tests)
    {
        if (t in _apps) continue;

        if (version_tests[t]())
        {

          /*
          console.log("vers1: "+ vers);
          console.log(_apps[t]);
          */
          for (vers in _apps[t])
          {
          //console.log("vers2: "+ t[vers]);
          var version = t + " " + vers;
          //console.log(version);
          }

          //console.log('_apps content:'+':'+_apps.content);

          var versName = t +" "+ vers;

          _apps[t] = -1;
          _apps[t] = vers;

          //  _apps.push(versName);
        }
    }


    //8 others
    // mention a found Duplicates only once:
    if(_apps['Magento_MRG'] == -1) delete _apps['Magento'];
    if(_apps['TS-Checkout-DIV + Produktdaten'] == -1) delete _apps['TS-Checkout-DIV'];
    if(_apps['Trustcard - DIV'] == -1) delete _apps['Trustcard via TB'];
    if(_apps['T-Online'] == -1) delete _apps['epages'];
    if(_apps['OpenCart'] == -1) delete _apps['Opencart'];
    if(_apps[/OpenCart-Journal2/] == -1) delete _apps['Opencart'];
    if(_apps[/OpenCart-Journal2/] == -1) delete _apps['OpenCart'];
    if(_apps[/OpenCart-Version/] == -1) delete _apps[/Opencart/];
    if(_apps[/OpenCart-Version/] == -1) delete _apps[/OpenCart/];
    if(_apps[/OpenCart-Version/] == /\s*(.*)/) delete _apps[/Opencart/];
    if(_apps['OpenCart-Journal-Version'] == -1) delete _apps[/OpenCart-Journal2/];
    if(_apps['OpenCart-Journal-Version'] == -1) delete _apps[/OpenCart-Journal3/];
    //if(_apps['SEOshop'] == null) {_apps['SEOshop'] = -1; delete _apps['Lightspeed'];}

    //other exceptions
    if(_apps['Smartstore-Image'] != null) delete _apps['Smartstore'];
    if(_apps['Smartstore-Image'] != null) delete _apps['Smartstore-Image'];

    // convert to array
    var jsonString = JSON.stringify(_apps);

    console.log(jsonString);
    // send back to background page
    var meta = document.getElementById('whatshop_meta');
    meta.content = jsonString;

    //Notify Background Page
    var done = document.createEvent('Event');
    done.initEvent('ready', true, true);
    meta.dispatchEvent(done);
} //end - immediate return
